name: Build
on:
  push:
    branches:
      - main
  schedule:
    # Biweekly on Friday night
    - cron: "0 0 * * 5#2"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build_svc_languagetool:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      context: ./svc-languagetool
      image_name: ${{ env.IMAGE_NAME }}-svc-languagetool

  build_svc_openrefine:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      context: ./svc-openrefine
      image_name: ${{ env.IMAGE_NAME }}-svc-openrefine

  build_box_qgis:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      context: ./box-qgis
      image_name: ${{ env.IMAGE_NAME }}-box-qgis

  build_box_zotero:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      context: ./box-zotero
      image_name: ${{ env.IMAGE_NAME }}-box-zotero
