name: Reusable Build

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      image_name:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2.13
        with:
          image: ${{ inputs.image_name }}
          tags: latest ${{ github.sha }}
          context: ${{ inputs.context }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          containerfiles: |
            Containerfile
      - name: Push To Registry
        id: push-image
        uses: redhat-actions/push-to-registry@v2.8
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Install Cosign
      #   uses: sigstore/cosign-installer@v3.5.0
      # - name: Sign container image
      #   run: |
      #     cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ inputs.image_name }}@${TAGS}
      #   env:
      #     TAGS: ${{ steps.push-image.outputs.digest }}
      #     COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
      #     COSIGN_EXPERIMENTAL: false
